{{-- resources/views/reports/exports/activities-pdf.blade.php --}}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Activities Report</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 11px;
            line-height: 1.4;
            color: #333;
        }

        h1 {
            text-align: center;
            color: #0d6efd;
            margin-bottom: 30px;
            font-size: 24px;
        }

        h2 {
            color: #198754;
            font-size: 18px;
            margin-top: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th {
            background: #0d6efd;
            color: white;
            padding: 8px;
            text-align: left;
            font-size: 10px;
        }

        td {
            padding: 6px;
            border-bottom: 1px solid #ddd;
            font-size: 9px;
        }

        tr:nth-child(even) {
            background: #f8f9fa;
        }

        .footer {
            text-align: center;
            color: #666;
            font-size: 9px;
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
        }

        .header-info {
            margin-bottom: 20px;
            padding: 10px;
            background: #f0f0f0;
            border-radius: 5px;
        }

        .summary-box {
            background: #e7f3ff;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }

        .summary-item {
            display: inline-block;
            margin-right: 30px;
        }

        .summary-label {
            font-size: 10px;
            color: #666;
        }

        .summary-value {
            font-size: 16px;
            font-weight: bold;
            color: #0d6efd;
        }
    </style>
</head>

<body>
    <h1>{{ config('app.name') }} - Activities Report</h1>

    <div class="header-info">
        <p><strong>Generated:</strong> {{ now()->format('F d, Y H:i:s') }}</p>
        <p><strong>Generated By:</strong> {{ Auth::user()->name }}</p>
        <p><strong>Date Range:</strong> {{ request('date_from', 'All time') }} to {{ request('date_to', 'Present') }}
        </p>
    </div>

    <div class="summary-box">
        <div class="summary-item">
            <div class="summary-label">Total Activities</div>
            <div class="summary-value">{{ $activities->count() }}</div>
        </div>
        <div class="summary-item">
            <div class="summary-label">Date Range</div>
            <div class="summary-value">
                {{ $activities->min('created_at')?->format('Y-m-d') ?? 'N/A' }} to
                {{ $activities->max('created_at')?->format('Y-m-d') ?? 'N/A' }}
            </div>
        </div>
    </div>

    <h2>Activity Logs</h2>

    <table>
        <thead>
            <tr>
                <th>Date/Time</th>
                <th>User</th>
                <th>Action</th>
                <th>Module</th>
                <th>Description</th>
                <th>IP Address</th>
                <th>Device</th>
                <th>Browser</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($activities as $activity)
                <tr>
                    <td>{{ $activity->created_at->format('Y-m-d H:i:s') }}</td>
                    <td>{{ $activity->user->name ?? 'System' }}</td>
                    <td>{{ ucfirst(str_replace('_', ' ', $activity->action)) }}</td>
                    <td>{{ ucfirst($activity->module) }}</td>
                    <td>{{ $activity->description }}</td>
                    <td>{{ $activity->ip_address ?? 'N/A' }}</td>
                    <td>
                        @if ($activity->device_type)
                            {{ ucfirst($activity->device_type) }}
                        @else
                            N/A
                        @endif
                    </td>
                    <td>{{ $activity->browser ?? 'N/A' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This report is generated automatically by {{ config('app.name') }}. For any inquiries, please contact the
            system administrator.</p>
        <p>© {{ date('Y') }} {{ config('app.name') }}. All rights reserved.</p>
    </div>
</body>

</html>
